<?php
//功能模块
return [
	'mod'=>[
		[
			'name'=>'会员中心',
			'pc_url'=>'/home/user/index.html',
			'wx_url'=>'/mobile/user/index.html',
		],
		[
			'name'=>'友情链接',
			'pc_url'=>'/index/link/index.html',
			'wx_url'=>'/mobile/link/index.html',
		],
		[
			'name'=>'人才招聘',
			'pc_url'=>'/index/job/index.html',
			'wx_url'=>'/mobile/job/index.html',
		],
		[
			'name'=>'留言板',
			'pc_url'=>'/index/guestboox/index.html',
			'wx_url'=>'/mobile/guestboox/index.html',
		],
		[
			'name'=>'站内信箱',
			'pc_url'=>'/index/mail/index.html',
			'wx_url'=>'/mobile/mail/index.html',
		],
		[
			'name'=>'活动模块',
			'pc_url'=>'/index/signup/index.html',
			'wx_url'=>'/mobile/signup/index.html',
		],
		[
			'name'=>'酒店模块',
			'pc_url'=>'/index/hotel/index.html',
			'wx_url'=>'/mobile/hotel/index.html',
		],
	],
	'art'=>[
		[
			'name'=>'文章首页',
			'pc_url'=>'/index/index/index.html',
			'wx_url'=>'/mobile/article/index.html',
		],
	],
	'mall'=>[
		[
			'name'=>'商城首页',
			'pc_url'=>'/home/index/index.html',
			'wx_url'=>'/mobile/index/index.html',
		],
		[
			'name'=>'促销模块',
			'pc_url'=>'/home/index/promoteList.html',
			'wx_url'=>'/mobile/index/promoteList.html',
		],
		[
			'name'=>'团购模块',
			'pc_url'=>'/home/activity/group_list.html',
			'wx_url'=>'/mobile/activity/group_list.html',
		],
		[
			'name'=>'积分商城',
			'pc_url'=>'/home/goods/integralMall.html',
			'wx_url'=>'/mobile/goods/integralMall.html',
		],
		[
			'name'=>'供应商',
			'pc_url'=>'/home/suppliers/index.html',
			'wx_url'=>'/mobile/suppliers/index.html',
		],
		[
			'name'=>'我的订单',
			'pc_url'=>'/home/user/order_list.html',
			'wx_url'=>'/mobile/user/order_list.html',
		],
	],
];
?>
